stages:
  - test
  - build
  - deploy

fast_api-unit-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - cd fast_api
    - pip install -r requirements.txt
    - python -m pytest

# Run flake8 to check for code quality
lint-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - pip install flake8
<<<<<<< HEAD
    - flake8 sample_service


fast_api-unit-test-job:
  image: module3-project-gamma-fast_api
  stage: test
  script:
    - fast_api
    - pip install -r requirements.txt
    - python -m pytest

=======
    - flake8 fast_api
>>>>>>> 99f890a413e9e0ad6002b2a314c096dafef10ffe

# Build the React/JavaScript front-end
build-front-end-job:
  stage: build
  image: node:lts-bullseye
  needs:
    - fast_api-unit-test-job
    - lint-test-job
  variables:
    PUBLIC_URL: https://ehong270.gitlab.io/module3-project-gamma/
    REACT_APP_SAMPLE_SERVICE_API_HOST: https://WEBSERVICE_NAME.onrender.com
  script:
    - cd ghi
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/build/

# Deploy the React/JavaScript front-end to GitLab pages
pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
    - mv ghi/build/ public
  artifacts:
    paths:
      - public
