volumes:
  trivia:
    external: true
services:
  fast_api:
    build:
      context: fast_api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./fast_api:/app
    environment:
      # DATABASE_URL: postgres://trivia_gbmj_user:0ltswBErYkmq0LmcfkQKpGBR775jJEqG@dpg-ce8gqgcgqg46a85fv88g-a/trivia_gbmj # production
      DATABASE_URL: postgres://trivia:trivia@trivia:5432/fast_api # development
      SIGNING_KEY: f9e6de79d378f063a372206326e59c36737f2b65f45d3765fd3856e16f7a993d6c90f5aa844692ec2895cd6c0051951b91dd97022fb227060ed04acee8e8d73a # development
      CORS_HOST: http://localhost:8000 # development

  db:
    build:
      context: data
      dockerfile: Dockerfile.dev
    volumes:
      - trivia:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: trivia
      POSTGRES_USER: trivia
      POSTGRES_DB: trivia
    ports:
      - "15432:5432"

  ghi:
    image: node:lts-bullseye
    command: bash -c "npm install && npm start"
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_FAST_API: http://localhost:8000
      CHOKIDAR_USEPOLLING: true # create-ui-app <= 5.x
      WATCHPACK_POLLING: true # create-ui-app >= 5.x
