volumes:
  trivia:
    external: true
services:
  fast_api:
    build:
      context: fast_api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./fast_api:/app
    environment:
      DATABASE_URL: postgresql://trivia:trivia@db/trivia

  db:
    build:
      context: data
      dockerfile: Dockerfile.dev
    volumes:
      - trivia:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: trivia
      POSTGRES_USER: trivia
      POSTGRES_DB: trivia
    ports:
      - "15432:5432"

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
